# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Check for the latest version
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [
          "--select", "E,F,W,C,N,B,B9,COM,PL,D",  # Include relevant checks from other tools
          "--fix",  # Auto-fix issues where possible
          "--line-length", "112",
        ]
        additional_dependencies: ["darglint"]  # Include any additional plugins

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "112"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
