# pyproject.toml

[tool.ruff]
line-length = 125

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C",
    "N",
    "B",
    "B9",
    "COM",
    "PL",
#    "D"
]
ignore = [
    "D102",
    "D105",
    "D107",
    "D203",
    "D212",
    "PLR0913",  # Ignore the rule for too many arguments
    "PLR2004",  # Ignore the rule for magic values
    "C901",  # Ingore the rule for to complex functions
    "E501", # Ignore the rule for line too long

]

[tool.black]
line-length = 125
skip-string-normalization = true
